# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, "7.0"

target 'httpConnectTest' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for httpConnectTest
  pod 'AFNetworking', '~> 2.0'

end
